version: "2"
networks:
  app-tier:
    driver: bridge
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    volumes:
      - ./apiusers/opt/apiusers
    command: yarn start